### ISSUE TITLE
Could not find derm7pt‘s pretrained model and could not open radpath's dataset URL.

### ISSUE THREAD

**Issue by waiterxiaoyy** [mayurmallya/DeepGuide#1]
Hello, author, in derm7pt, I could not find the pre-trained models 7pt_F_diag_T_mgmt_F_exported.h5 and 7pt_T_diag_T_mgmt_T_exported.h5, where can I download them or can you provide these two pre-trained models for me? In addition, for radpath, I couldn't open the URL http://miccai2020-data.eastus.cloudapp.azure.com/, so I couldn't download the dataset. Could you also provide this dataset for me? My email: waiterxiaoyy@qq.com, if you are willing to help me, you can send them to my email. Thank you very much for your work and help.

**Comment by mayurmallya** [comment]
Hi there, thank you for raising the issue.

I have added the link to the pre-trained model for the Derm7pt dataset- https://drive.google.com/drive/folders/19sTB49N7SBQBRO-yP05957yzZNuEk_Cz?usp=sharing

With respect to the RadPath dataset, yes, you are correct. The website is down at the moment and I too am unable to download the data. I would highly recommend contacting the organizers of the RadPath challenge. Please see this link (https://zenodo.org/record/3718894) for more information on who to contact. If it doesn't work, let me know, and I will try to share the dataset with you directly.
